apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: productos  
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/productos/WSMovimientos
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:      
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: productos    
spec:
  replicas: 1
  selector:
    deploymentconfig: WSMovimientos
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:      
      labels:
        app: WSMovimientos
        deploymentconfig: WSMovimientos
    spec:
      containers:
      - env:
        - name : DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "false"
        - name : TZ
          value: America/Guayaquil
        image: docker-registry.default.svc:5000/productos/WSMovimientos
        imagePullPolicy: Always
        name: WSMovimientos
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 245Mi
          requests:
            cpu: 200m
            memory: 200Mi        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/configs/catalogo
          name: volume-catalogo
        - mountPath: /opt/app-root/configs/logs
          name: volume-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: catalogos
        name: volume-catalogo
      - configMap:
          defaultMode: 420
          name: logconfiguracion
        name: volume-logs
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - WSMovimientos
        from:
          kind: ImageStreamTag
          name: 'WSMovimientos:latest'
          namespace: productos
      type: ImageChange
    - type: ConfigChange
  test: false
---
apiVersion: v1
kind: Service
metadata:    
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: productos    
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: WSMovimientos
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:    
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: productos    
spec:
  host: WSMovimientos-productos.apps.desa.bpichincha.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: WSMovimientos
    weight: 100
  wildcardPolicy: None