apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: clientes  
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/clientes/WSMovimientos
---
apiVersion: v1
kind: Secret
metadata:
  name: ConexionServicioSipecom
type: Opaque 
stringData:
  OPENSHIFT-SEG-API-URL-SIPECOM: __OPENSHIFT-SEG-API-URL-SIPECOM__
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:      
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: clientes    
spec:
  replicas: 1
  selector:
    deploymentconfig: WSMovimientos
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:      
      labels:
        app: WSMovimientos
        deploymentconfig: WSMovimientos
    spec:
      containers:
      - env:
        - name : DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "false"
        - name : TZ
          value: America/Guayaquil
        - name : OPENSHIFT-SEG-API-URL-SIPECOM
          valueFrom:
            secretKeyRef:
              name: ConexionServicioSipecom
              key: OPENSHIFT-SEG-API-URL-SIPECOM
        image: docker-registry.default.svc:5000/clientes/WSMovimientos
        imagePullPolicy: Always
        name: WSMovimientos
        readinessProbe:
          httpGet:   
            path: /api/v1/ServicioBase/HealthChecksServicio
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 4
        livenessProbe:
          httpGet:   
            path: /api/v1/ServicioBase/HealthChecks
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 4
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/configs/centralizada
          name: volume-centralizada
        - mountPath: /opt/app-root/configs/catalogo
          name: volume-catalogo
        - mountPath: /opt/app-root/configs/logs
          name: volume-logs
        - mountPath: /opt/app-root/configs/servicio
          name: volume-servicio
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: centralizada
        name: volume-centralizada
      - configMap:
          defaultMode: 420
          name: catalogos
        name: volume-catalogo
      - configMap:
          defaultMode: 420
          name: logconfiguracion
        name: volume-logs
      - configMap:
          defaultMode: 420
          name: WSMovimientos
        name: volume-servicio
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - WSMovimientos
        from:
          kind: ImageStreamTag
          name: 'WSMovimientos:latest'
          namespace: clientes
      type: ImageChange
    - type: ConfigChange
  test: false
---
apiVersion: v1
kind: Service
metadata:    
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: clientes    
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: WSMovimientos
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:    
  labels:
    app: WSMovimientos
  name: WSMovimientos
  namespace: clientes    
spec:
  host: WSMovimientos-clientes.apps.test.bpichincha.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: WSMovimientos
    weight: 100
  wildcardPolicy: None