USE [BDD_MOVIMIENTOS]
GO
/****** Object:  Table [dbo].[BM_CLIENTE]    Script Date: 15 may. 2023 08:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BM_CLIENTE](
	[ID_CLIENTE] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_PERSONA] [bigint] NOT NULL,
	[CONTRASENIA] [varchar](50) NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BM_CUENTA]    Script Date: 15 may. 2023 08:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BM_CUENTA](
	[ID_CUENTA] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_PERSONA] [bigint] NOT NULL,
	[NUMERO_CUENTA] [int] NOT NULL,
	[TIPO_CUENTA] [varchar](3) NOT NULL,
	[SALDO_INICIAL] [decimal](10, 2) NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CUENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BM_MOVIMIENTOS]    Script Date: 15 may. 2023 08:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BM_MOVIMIENTOS](
	[ID_MOVIMIENTOS] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_CUENTA] [bigint] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[TIPO] [nvarchar](3) NOT NULL,
	[VALOR] [decimal](10, 2) NOT NULL,
	[SALDO] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MOVIMIENTOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BM_PERSONA]    Script Date: 15 may. 2023 08:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BM_PERSONA](
	[ID_PERSONA] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](150) NOT NULL,
	[GENERO] [char](1) NOT NULL,
	[EDAD] [int] NOT NULL,
	[IDENTIFICACION] [varchar](15) NOT NULL,
	[DIRECCION] [varchar](250) NULL,
	[TELEFONO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[BM_CLIENTE] ON 
GO
INSERT [dbo].[BM_CLIENTE] ([ID_CLIENTE], [ID_PERSONA], [CONTRASENIA], [ESTADO]) VALUES (1, 1, N'1234', 1)
GO
INSERT [dbo].[BM_CLIENTE] ([ID_CLIENTE], [ID_PERSONA], [CONTRASENIA], [ESTADO]) VALUES (2, 1, N'5678', 1)
GO
INSERT [dbo].[BM_CLIENTE] ([ID_CLIENTE], [ID_PERSONA], [CONTRASENIA], [ESTADO]) VALUES (3, 1, N'1245', 1)
GO
SET IDENTITY_INSERT [dbo].[BM_CLIENTE] OFF
GO
SET IDENTITY_INSERT [dbo].[BM_CUENTA] ON 
GO
INSERT [dbo].[BM_CUENTA] ([ID_CUENTA], [ID_PERSONA], [NUMERO_CUENTA], [TIPO_CUENTA], [SALDO_INICIAL], [ESTADO]) VALUES (1, 1, 478758, N'AHO', CAST(2000.00 AS Decimal(10, 2)), 1)
GO
INSERT [dbo].[BM_CUENTA] ([ID_CUENTA], [ID_PERSONA], [NUMERO_CUENTA], [TIPO_CUENTA], [SALDO_INICIAL], [ESTADO]) VALUES (2, 2, 225487, N'COR', CAST(100.00 AS Decimal(10, 2)), 1)
GO
INSERT [dbo].[BM_CUENTA] ([ID_CUENTA], [ID_PERSONA], [NUMERO_CUENTA], [TIPO_CUENTA], [SALDO_INICIAL], [ESTADO]) VALUES (3, 3, 495878, N'AHO', CAST(0.00 AS Decimal(10, 2)), 1)
GO
INSERT [dbo].[BM_CUENTA] ([ID_CUENTA], [ID_PERSONA], [NUMERO_CUENTA], [TIPO_CUENTA], [SALDO_INICIAL], [ESTADO]) VALUES (4, 2, 496825, N'AHO', CAST(540.00 AS Decimal(10, 2)), 1)
GO
INSERT [dbo].[BM_CUENTA] ([ID_CUENTA], [ID_PERSONA], [NUMERO_CUENTA], [TIPO_CUENTA], [SALDO_INICIAL], [ESTADO]) VALUES (5, 1, 585545, N'COR', CAST(1000.00 AS Decimal(10, 2)), 1)
GO
SET IDENTITY_INSERT [dbo].[BM_CUENTA] OFF
GO
SET IDENTITY_INSERT [dbo].[BM_MOVIMIENTOS] ON 
GO
INSERT [dbo].[BM_MOVIMIENTOS] ([ID_MOVIMIENTOS], [ID_CUENTA], [FECHA], [TIPO], [VALOR], [SALDO]) VALUES (1, 1, CAST(N'2023-05-15T00:37:59.760' AS DateTime), N'RET', CAST(575.00 AS Decimal(10, 2)), CAST(1425.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[BM_MOVIMIENTOS] ([ID_MOVIMIENTOS], [ID_CUENTA], [FECHA], [TIPO], [VALOR], [SALDO]) VALUES (2, 2, CAST(N'2023-05-15T00:39:17.040' AS DateTime), N'DEP', CAST(600.00 AS Decimal(10, 2)), CAST(700.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[BM_MOVIMIENTOS] ([ID_MOVIMIENTOS], [ID_CUENTA], [FECHA], [TIPO], [VALOR], [SALDO]) VALUES (3, 3, CAST(N'2023-05-15T00:40:11.983' AS DateTime), N'DEP', CAST(150.00 AS Decimal(10, 2)), CAST(150.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[BM_MOVIMIENTOS] ([ID_MOVIMIENTOS], [ID_CUENTA], [FECHA], [TIPO], [VALOR], [SALDO]) VALUES (4, 4, CAST(N'2023-05-15T00:42:27.653' AS DateTime), N'RET', CAST(540.00 AS Decimal(10, 2)), CAST(0.00 AS Decimal(10, 2)))
GO
SET IDENTITY_INSERT [dbo].[BM_MOVIMIENTOS] OFF
GO
SET IDENTITY_INSERT [dbo].[BM_PERSONA] ON 
GO
INSERT [dbo].[BM_PERSONA] ([ID_PERSONA], [NOMBRE], [GENERO], [EDAD], [IDENTIFICACION], [DIRECCION], [TELEFONO]) VALUES (1, N'Jose  Lema', N'H', 30, N'1718333331', N'Otavalo sn y principal', 98254785)
GO
INSERT [dbo].[BM_PERSONA] ([ID_PERSONA], [NOMBRE], [GENERO], [EDAD], [IDENTIFICACION], [DIRECCION], [TELEFONO]) VALUES (2, N'Marianela Montalvo', N'H', 30, N'1718333332', N'Amazonas  y  NNUU', 97548965)
GO
INSERT [dbo].[BM_PERSONA] ([ID_PERSONA], [NOMBRE], [GENERO], [EDAD], [IDENTIFICACION], [DIRECCION], [TELEFONO]) VALUES (3, N'Juan Osorio', N'H', 30, N'1718333333', N'13 junio y Equinoccial', 98874587)
GO
SET IDENTITY_INSERT [dbo].[BM_PERSONA] OFF
GO
ALTER TABLE [dbo].[BM_CLIENTE] ADD  DEFAULT ('1') FOR [ESTADO]
GO
ALTER TABLE [dbo].[BM_CUENTA] ADD  DEFAULT ('0') FOR [SALDO_INICIAL]
GO
ALTER TABLE [dbo].[BM_CUENTA] ADD  DEFAULT ('1') FOR [ESTADO]
GO
ALTER TABLE [dbo].[BM_MOVIMIENTOS] ADD  DEFAULT (getdate()) FOR [FECHA]
GO
ALTER TABLE [dbo].[BM_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_BM_CLIENTE_BM_PERSONA] FOREIGN KEY([ID_PERSONA])
REFERENCES [dbo].[BM_PERSONA] ([ID_PERSONA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BM_CLIENTE] CHECK CONSTRAINT [FK_BM_CLIENTE_BM_PERSONA]
GO
ALTER TABLE [dbo].[BM_CUENTA]  WITH CHECK ADD  CONSTRAINT [FK_BM_CUENTA_BM_PERSONA] FOREIGN KEY([ID_PERSONA])
REFERENCES [dbo].[BM_PERSONA] ([ID_PERSONA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BM_CUENTA] CHECK CONSTRAINT [FK_BM_CUENTA_BM_PERSONA]
GO
ALTER TABLE [dbo].[BM_MOVIMIENTOS]  WITH CHECK ADD  CONSTRAINT [FK_BM_MOVIMIENTOS_BM_CUENTA] FOREIGN KEY([ID_CUENTA])
REFERENCES [dbo].[BM_CUENTA] ([ID_CUENTA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BM_MOVIMIENTOS] CHECK CONSTRAINT [FK_BM_MOVIMIENTOS_BM_CUENTA]
GO
